baseURL = "https://nifi.apache.org"
title = "Apache NiFi"
copyright = "The Apache Software Foundation"
languageCode = "en"
enableRobotsTXT = true
disableBrowserError = true
disableKinds = ["RSS", "taxonomy", "term"]
enableGitInfo = true
theme = "nifi"
enableInlineShortcodes = true
disablePathToLower = true

[markup.goldmark.renderer]
unsafe = true

[params]
description = "Apache NiFi is an easy to use, powerful, and reliable system to process and distribute data"
keywords = "apache,nifi,data,distribution"
twitterUser = "apachenifi"
projectBrand = "/images/project-brand.jpg"

repositoryUrl = "https://github.com/apache/nifi"
repositorySourceBranch = "main"

siteRepositoryUrl = "https://github.com/apache/nifi-site"
siteRepositorySourceBranch = "main"
assets = "assets"

matomoSiteId = 28
productionHost = "nifi.apache.org"

staticDocsPath = "/nifi-docs"

apacheFoundationGroupsUrl = "https://projects.apache.org/json/foundation/groups.json"
apacheFoundationPeopleNameUrl = "https://projects.apache.org/json/foundation/people_name.json"

dynamicDownloadPathUrl = "https://www.apache.org/dyn/closer.lua?path=/nifi"
downloadPathUrl = "https://downloads.apache.org/nifi"
archiveDownloadPathUrl = "https://archive.apache.org/dist/nifi"
mavenCentralDownloadPathUrl = "https://repo1.maven.org/maven2/org/apache/nifi"

currentProjectVersion = "2.7.2"
currentProjectVersionReleased = "2025-12-17"

previousProjectVersion = "1.28.1"
previousProjectVersionReleased = "2024-11-19"

minifiCppCurrentProjectVersion = "0.99.2"
minifiCppCurrentProjectVersionReleased = "2025-10-06"

minifiCppPreviousProjectVersion = "0.99.1"
minifiCppPreviousProjectVersionReleased = "2025-02-05"

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "prebuild/public/components"
    target = "content/components"
  [[module.mounts]]
    source = "prebuild/public/html"
    target = "static/nifi-docs"

[menu]
  [[menu.main]]
    name = 'NiFi Version 2 Documentation'
    url = '/components/'
    weight = 1
    parent = 'Documentation'
  [[menu.main]]
    name = 'Wiki'
    url = 'https://cwiki.apache.org/confluence/display/NIFI'
    weight = 3
    parent = 'Documentation'
    [menu.main.params]
      external = true
  [[menu.main]]
    name = 'Contributing'
    url = 'https://cwiki.apache.org/confluence/display/NIFI/Contributor+Guide'
    weight = 1
    parent = 'Development'
    [menu.main.params]
      external = true
  [[menu.main]]
    name = 'Issues'
    url = 'https://issues.apache.org/jira/browse/NIFI'
    weight = 2
    parent = 'Development'
    [menu.main.params]
      external = true
  [[menu.main]]
    name = 'Source'
    url = 'https://github.com/apache/nifi'
    weight = 3
    parent = 'Development'
    [menu.main.params]
      external = true
  [[menu.main]]
    name = 'Team'
    url = '/community'
    weight = 3
    parent = 'Community'
  [[menu.main]]
    name = 'Apache'
    url = 'https://www.apache.org'
  [[menu.main]]
    name = 'Events'
    url = 'https://apache.org/events/current-event'
    parent = 'Apache'
    [menu.main.params]
      external = true
  [[menu.main]]
    name = 'License'
    url = 'https://www.apache.org/licenses'
    parent = 'Apache'
    [menu.main.params]
      external = true
  [[menu.main]]
    name = 'Privacy'
    url = 'https://privacy.apache.org/policies/privacy-policy-public.html'
    parent = 'Apache'
    [menu.main.params]
      external = true
  [[menu.main]]
    name = 'Sponsorship'
    url = 'https://www.apache.org/foundation/sponsorship.html'
    parent = 'Apache'
    [menu.main.params]
      external = true
  [[menu.main]]
    name = 'Thanks'
    url = 'https://www.apache.org/foundation/thanks.html'
    parent = 'Apache'
    [menu.main.params]
      external = true

[mediaTypes]
  [mediaTypes."text/yaml"]
    suffixes = ["yaml", "yml"]

[outputFormats]
  [outputFormats.YAML]
    mediaType = "text/yaml"
    isPlainText = true
    path = "/"
